# Generated by Django 3.1.1 on 2021-01-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=75)),
                ('name', models.CharField(max_length=75)),
                ('occupation', models.CharField(max_length=50)),
                ('bplace_country', models.CharField(max_length=50)),
                ('birthdate', models.DateTimeField()),
                ('birthyear', models.IntegerField()),
                ('dplace_name', models.CharField(max_length=50)),
                ('dplace_country', models.CharField(max_length=50)),
                ('deathdate', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
            ],
        ),
    ]
