# Generated by Django 3.1.1 on 2021-01-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthyear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='deathdate',
            field=models.DateTimeField(null=True),
        ),
    ]
